version: '3.3'
services:
    quant1-frpc:
        environment:
            - SERVER_ADDR=194.163.176.185
            - SERVER_PORT=7000
            - QUANT1_USER=""
            - QUANT1_ACESS_TOKEN=""
        container_name: Quant1-frpc
        stdin_open: true
        tty: true
        network_mode: host
        image: registry.quant1.com.br/arthur/quant1-frpc
