version: '3.3'
services:
  quant1-frp-client:
    image: registry.quant1.com.br/arthur/quant1-frpc
    build: .
    command: ["-c", "./quant1-frpc"]
    secrets:
      - QUANT1_CREDENTIALS
    environment:
      - PROXY_NAME=${PROXY_NAME}
      - PROXY_TYPE=${PROXY_TYPE}
      - PROXY_LOCAL_IP=${PROXY_LOCAL_IP}
      - PROXY_LOCAL_PORT=${PROXY_LOCAL_PORT}
    container_name: Quant1-frpc
    tty: true
    stdin_open: true
    network_mode: host
secrets:
  QUANT1_CREDENTIALS:
    file: ./.credentials
