version: '3.3'
services:
  frp-client:
    image: frp-client
    command: ["-c", "./my-frpc"]
    volumes:
      - ./server_config:/frp/server_config
    secrets:
      - CREDENTIALS
    environment:
      - PROXY_NAME=${PROXY_NAME}
      - PROXY_TYPE=${PROXY_TYPE}
      - PROXY_LOCAL_IP=${PROXY_LOCAL_IP}
      - PROXY_LOCAL_PORT=${PROXY_LOCAL_PORT}
      - CUSTOM_APP_URL=${CUSTOM_APP_URL}
    container_name: my-frp-client
    tty: true
    stdin_open: true
    network_mode: host
secrets:
  CREDENTIALS:
    file: ./.credentials
