serverAddr = "frp-server"
serverPort = 7000
log_file = "/var/log/frps.log"
log_level = "trace"
log.maxDays = 3
[[proxies]]
name = "user-proxy"
type = "http"
localPort = 22
localIp = "0.0.0.0"
customDomains = ["my-app.test"]
