name: Docker Build Main

on:
  push:
    branches:
      - 'main'
jobs:
  docker-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: set lower case repository
        run: |
          echo "REPOSITORY_LC=${REPOSITORY,,}" >>${GITHUB_ENV}
        env:
          REPOSITORY: '${{ github.repository }}'

      - name: Build and push frp-client image
        run: |
          docker build -t ghcr.io/${REPOSITORY_LC}:frp-client .
          docker push ghcr.io/${REPOSITORY_LC}:frp-client

          # Tagging the latest image
          docker tag ghcr.io/${REPOSITORY_LC}:frp-client ghcr.io/${REPOSITORY_LC}:latest
          docker push ghcr.io/${REPOSITORY_LC}:latest